### ISSUE TITLE
Unable to import module 'main': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)

### ISSUE THREAD

**Issue by martinklie** [aws-samples/amazon-textract-idp-cdk-constructs#113]
The install went well but I'm running into an error with the OpenSearchPushInvoke with the test moby pdf or another jpg I tried.  Both fail at the same step with the same error (below)
{
  "errorMessage": "Unable to import module 'main': cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/var/task/urllib3/util/ssl_.py)",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "163068ee-c790-4a96-9b35-971dc052c4da",
  "stackTrace": []
}

**Comment by schadem** [comment]
fixed by pull request https://github.com/aws-solutions-library-samples/guidance-for-low-code-intelligent-document-processing-on-aws/issues/37
