### ISSUE TITLE
DeprecationError for PyPDF2.PdfFileReader in decider_main.py

### ISSUE THREAD

**Issue by aditirajnish** [aws-samples/amazon-textract-idp-cdk-constructs#15]
Getting this DeprecationError message when executing the Document Splitter Workflow from the IDP workshop, causing the DocumentSplitterWorkflow-Decider step to fail (https://catalog.us-east-1.prod.workshops.aws/workshops/f2dd7c46-e022-4f9c-8399-dcad742be516/en-US/lab-6/step-6d):

{
  "errorMessage": "PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.",
  "errorType": "DeprecationError",
  "requestId": "ee10797f-9309-4235-90fe-67b9e6032836",
  "stackTrace": [
    "  File \"/var/task/decider_main.py\", line 125, in lambda_handler\n    numberOfPages = get_number_of_pages(file_bytes=file_bytes, mime=mime)\n",
    "  File \"/var/task/decider_main.py\", line 63, in get_number_of_pages\n    pdf_reader = PdfFileReader(input_pdf_file)\n",
    "  File \"/var/task/PyPDF2/_reader.py\", line 1974, in __init__\n    deprecation_with_replacement(\"PdfFileReader\", \"PdfReader\", \"3.0.0\")\n",
    "  File \"/var/task/PyPDF2/_utils.py\", line 369, in deprecation_with_replacement\n    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))\n",
    "  File \"/var/task/PyPDF2/_utils.py\", line 351, in deprecation\n    raise DeprecationError(msg)\n"
  ]
}

Assuming that the decider_main.py file being referred to is this one: https://github.com/aws-samples/amazon-textract-idp-cdk-constructs/blob/main/lambda/decider/app/decider_main.py

**Comment by MartinThoma** [comment]
Here are your options:

1. Downgrade to `PyPDF2<3.0.0`
2. Upgrade your code (replace `PdfFileReader` by `PdfReader`; potentially more)
3. Replace `PyPDF2` by `pypdf` + step (2)

**Comment by anjanvb** [comment]
@aditirajnish The issue has been resolved in the latest release.
